### ISSUE TITLE
Postgres container won't start ...

### ISSUE THREAD

**Issue by mhubig** [mhubig/atlassian#1]
Starting the database (within boot2docker) container with:

``` bash
$ docker-compose rm -f
$ docker-compose -f docker-compose-dev.yml run database
...
cat: -: No such file or directory
```

fails, while starting it with:

``` bash
$ docker-compose rm -f
$ docker-compose -f docker-compose-dev.yml run database sh docker-entrypoint.sh postgres
...
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
```

works ...

**Comment by bastianwegge** [comment]
Hey,

so the point is that the postgres container won't start on boot2docker, due to security issues I guess. The only error message I get is the following:

```
database_1 | postgres cannot access the server configuration file "/var/lib/postgresql/data/postgresql.conf": No such file or directory
```

This is just a problem on the local machine. Just tried the installation on Ubuntu 14.04 in a closed environment and it seems to be working.

**Comment by mhubig** [comment]
```
database_1 | postgres cannot access the server configuration file "/var/lib/postgresql/data/postgresql.conf": No such file or directory
```

This error is related to a "read-only-ish" volume when using boot2docker. You can use the `-f docker-compose-dev.yml` switch which avoids using the read-only data-volume for the postgres container.
